### PR TITLE
Move to public registry

### PR DESCRIPTION
**Pull request by gitkvark**

### CODE REVIEW

**Comment by silopolis** [comment]
For my education, what are aliases here for?

Could we add some kind of (simple) check to this PR? Link a request to the repository or something?

**Review by silopolis — COMMENTED** [review]
For my education, what are aliases here for?

Could we add some kind of (simple) check to this PR? Link a request to the repository or something?

**Comment by gitkvark** [comment]
> For my education, what are aliases here for?
It's a random generated string by AWS at the time of the public registry creation. I added a comment.

> Could we add some kind of (simple) check to this PR? Link a request to the repository or something?
Sure. How do you do that? :)

**Comment by silopolis** [comment]
> > For my education, what are aliases here for?
> 
> It's a random generated string by AWS at the time of the public registry creation. I added a comment.

OK thanks.

> > Could we add some kind of (simple) check to this PR? Link a request to the repository or something?
> 
> Sure. How do you do that? :)

Well, that was actually my question lol ;)
An additional step querying the registry using `docker search` or the API directly (https://www.baeldung.com/ops/docker-registry-api-list-images-tags) to check if the image is found there.
A step further would be a `docker pull` to verify the image can be retrieved.

As, ideally, we should know from the build stage that the image can be run (add `docker run` as a test there), this should provide for a functionally tested build and upload pipeline.

This would be the basis, later, other non-functional tests (image security scanning, etc.) could be added as improvements.

**Comment by gitkvark** [comment]
Something like this?
https://blog.brazdeikis.io/posts/docker-image-tests/

**Comment by silopolis** [comment]
Nice find :heart_eyes: 
Perfect reference for "level 2" functional testing.

Level 3 could be using some kind of infrastructure testing framework like Goss/InSpec/Serverspec

Security wise, testing with Bif, Grype, Dockle, and signing with Cosign would be nice evolutions.

But for starter, simply testing that:
- following `build`, `run` works
- following `push`
  - `search` returns proper image ref and info
  - `pull` works as expected

would already be very nice! :)

**Review by JoAngel8 — APPROVED** [review]
review done Looks Good for me. - if ok for you Jacint, you can merge it, please.

**Comment by gitkvark** [comment]
I'd say let's merge this and come back to testing the image if we have the time.

**Review by silopolis — APPROVED** [review]

**Review by JoAngel8 — COMMENTED** [review]
ok let's go.

**Pull request merged**
