### PR TITLE
docs: documentation system initial PR

### PR DESCRIPTION
**Pull request by silopolis**
Quite a bunch to say on this one...

I'll keep it for future content improvements if you allow me...

Please review generated site at https://devops-boot.netlify.app/

Will put together a simple and short style guide if needed.

Hope y'all dig it :)

### CODE REVIEW

**Review by gitkvark — APPROVED** [review]
On my, this is beautiful!

**Comment by JoAngel8** [comment]
Looks good. docs are online, availables and readable.

**Review by JoAngel8 — APPROVED** [review]
Review done by the online docs.

**Comment by silopolis** [comment]
Thanks for the review guys :pray:

**Pull request merged**
